version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: challenge3-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-service
    networks:
      - challenge3-network

  node-service:
    image: node:14
    container_name: challenge3-node-service
    working_dir: /usr/src/app
    volumes:
      - ./node-app:/usr/src/app
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - challenge3-network

  db:
    image: mariadb:latest
    container_name: challenge3-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      retries: 5
      start_period: 120s
      timeout: 20s
    networks:
      - challenge3-network

volumes:
  db_data:
    driver: local

networks:
  challenge3-network:
    driver: bridge
